name: 'gpr tool'
description: 'Run the gpr tool'
inputs:
  command:
    description: 'gpr sub-command'
    required: false
    default: list
  token:
    description: 'PAT to use'
    required: false
    default: ${{ github.token }}
  path:
    description: 'Path to packages'
    required: true
  options:
    description: 'Any extra options'
    required: false
runs:
  using: "composite"
  steps: 
    - run: dotnet exec ${{ github.action_path }}/src/GprTool/bin/Release/netcoreapp3.0/publish/gpr.dll ${{ inputs.command }} ${{ inputs.path }} -k ${{ inputs.token }} ${{ inputs.options }}
      shell: bash
      env:
        DOTNET_NOLOGO: true
