name: GitHub Action

on: [push]

env:
  NBGV_VERSION: 3.1.91
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1 
  
  GprToolCsprojPath: src/GprTool/GprTool.csproj
  GprToolTestsCsprojPath: test/GprTool.Tests/GprTool.Tests.csproj
  TestResultsDirectory: TestResults

jobs:

  build-and-test:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup dotnet using global.json
        uses: actions/setup-dotnet@v1.5.0
    
      - uses: dotnet/nbgv@v0.3.1
        with:
          setAllVars: true
          
      - name: Build
        shell: bash
        run: |
          dotnet build $GprToolCsprojPath -c Release -p:GeneratePackageOnBuild=True
          
      - name: Test
        shell: bash
        run: |
          dotnet test $GprToolTestsCsprojPath -c Release --logger:nunit --verbosity normal -p:IsRunningTests=True --results-directory $TestResultsDirectory
